metrics_definition_prompt = {
  "swap_free": "Available swap memory (MB)",
  "network": "Allowed transmission and reception capacity (bytes)",
  "rx_discards_delta": "Received discarded bytes (bytes)",
  "cpu_user": "CPU usage by user processes (%)",
  "rx_pkts_delta": "The number of received packets",
  "rx_bytes_delta": "Received bytes (bytes)",
  "cpu_usage": "Total CPU usage (user + system + wait) (%)",
  "tx_bytes_delta": "Transmitted bytes (bytes)",
  "cpu_idle": "Available CPU percentage (%)",
  "memory_usage": "Physical memory usage (%)",
  "cpu_system": "CPU usage by system processes (%)",
  "swap_used": "Used swap memory (MB)",
  "phy_total": "Total physical memory (MB)",
  "swap_total": "Total swap memory (MB)",
  "cpu_usage_max": "Maximum total CPU usage (user + system + wait) (%)",
  "phy_free": "Available physical memory (MB)",
  "memory_used": "Used physical memory (MB)",
  "rx_errors_delta": "Number of network receive errors",
  "tx_errors_delta": "Number of network transmit errors",
  "tx_discards_delta": "Number of discarded network receive packets",
  "tx_pkts_delta": "Number of network receive packets",
  "swap_usage": "Percentage of swap space usage on disk (%)",

  "tps": "Transactions per second (txn_end_count)",
  "os_cpu_usage": "OS CPU usage (%)",
  "sql_prepare_count": "Total number of SQL prepare statements",
  "sql_fetch_count": "Total number of SQL fetch operations",
  "jvm_gc_time": "Garbage collection time (ms)",
  "active_db_sessions": "The number of active database connections",
  "active_txns": "The number of active service/transactions",
  "os_used_memory": "OS memory usage (MB)",
  "sql_elapse": "Total SQL execution time (ms)",
  "jvm_thread_count": "The number of active threads",
  "request_rate": "The number of requests processed",
  "jvm_gc_count": "The number of garbage collection occurrences",
  "os_memory_usage": "OS memory usage percentage (%)",
  "jvm_heap_usage": "JVM heap memory usage (%)",
  "open_socket_count": "The number of open sockets",
  "txn_elapse": "Transaction execution time (ms)",
  "sql_exec_count": "Total number of SQL executions",
  "jvm_cpu_usage": "JVM CPU usage (%)",

  "elapse_avg": "Average execution time for the entire E2E section (ms)",
  "elapse06_avg": "Average execution time for MCI (ms)",
  "elapse07_avg": "Average execution time for FEP (ms)",
  "elapse08_avg": "Average execution time for EAI (ms)",
  "sql_elapse06": "Average execution time for MCI SQL (ms)",
  "sql_elapse07": "Average execution time for FEP SQL (ms)",
  "sql_elapse08": "Average execution time for EAI SQL (ms)",
  "error_count": "The number of errors in the entire E2E section",
  "exec_count": "The number of executions in the entire E2E section",
  "elapse_over_count": "The number of transactions in one minute where the transaction execution time (ms) exceeded the threshold",

  "enqueue_requests": "Queue allocation request count",
  "user_calls": "User Calls per second for Oracle",
  "library_cache_lock": "Library cache lock event wait time (ms)",
  "consistent_gets": "The number of consistent get requests",
  "non_idle_wait_time": "Non-idle wait time",
  "active_sessions": "The number of active sessions",
  "session_logical_reads": "The number of blocks read from memory per second",
  "file_io_wait_time": "Total I/O wait time",
  "enqueue_waits": "Queue allocation wait time",
  "physical_writes_direct": "The number of blocks written directly to disk",
  "lock_waiting_sessions": "The number of waiting sessions",
  "cpu_used_by_this_session": "CPU time used by the session",
  "user_commits": "The number of transaction commits performed",
  "physical_writes": "Total number of data blocks written to disk",
  "log_file_sync": "Log file sync event wait time",
  "concurrency_wait_time": "Concurrency wait time",
  "buffer_busy_waits": "Buffer busy waits event duration",
  "recursive_calls": "The number of recursive calls",
  "row_cache_lock": "Row cache lock event wait time",
  "execute_count": "The number of SQL executions",
  "physical_reads": "The number of blocks read from disk per second",
  "file_io_service_time": "Total I/O service time",
  "physical_reads_direct": "The number of reads directly from disk",
  "cursor_pin_s_wait_on_x": "The wait time for other sessions to access the cursor",
  "db_block_gets": "The number of data in the current block",
  "db_file_sequential_read": "Time taken for disk I/O completion (s)",
  "db_block_changes": "The number of changes to the DB block",
  "parse_time_elapsed": "Time taken to parse the SQL requested by the user",
  "user_rollbacks": "The number of transaction rollbacks performed",
  "db_file_scattered_read": "Wait time for completion of multi-block I/O request",
  "db_time": "DB response time",
  "gc_cr_request": "Wait event (in seconds) that occurs when a process requests the master node to send a data block in CR mode because the required single data block is not present in the local cache, and waits for the response.",
  "log_buffer_space": "Wait event (in seconds) that occurs when there is no available space in the log buffer while trying to write a new redo record.",
  "free_buffer_waits": "Wait event (in seconds) that occurs when a free buffer cannot be found in the buffer cache for reading a data block or creating a consistent read (CR) image."
}